# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaterMyPlants' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaterMyPlants

  pod 'SwiftLint'

  target 'WaterMyPlantsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WaterMyPlantsUITests' do
    # Pods for testing
  end

end
